server:
    port: 8081

spring:
    hikari:
        connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: none
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://postgres-user:5432/user_db
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    flyway:
        enabled: true
        locations: classpath:db/migration

jwt:
    password:
        encoder:
            secret: ${JWT_PASSWORD_SECRET}
            iteration: 64
            key-length: 256
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    issuer: SECURITY_SERVICE
