server:
    port: 8081

spring:
    hikari:
        connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: none
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://postgres-user:5432/user_db
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    flyway:
        enabled: true
        locations: classpath:db/migration

jwt:
    password:
        encoder:
            secret: F2K2DZ82odq$13e8aENggaMbb_fAkl-nJL4AEVBX43g
            iteration: 64
            key-length: 256
    secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f86df20a499a7d3f91ff2a7c
    expiration: 7200
    issuer: SECURITY_SERVICE
